inlcuded test proj

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -34,22 +34,21 @@ phases:
                     # /d.sonar.qualitygate.timeout=300
             - dotnet build
             - dotnet test
-            - dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'
-            # - curl $Sonar_Host/api/qualitygates/project_status?projectKey=$Sonar_Project >result.json
-            # - cat result.json
-            # - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
-            # - dotnet test -c Release ./test/ClassroomApp.Tests.csproj --logger trx --results-directory ./testresults            
+            - dotnet-coverage collect 'dotnet test' -f xml  -o 'coverage.xml'                     
             - dotnet sonarscanner end /d:sonar.login=$Sonar_AccessToken
-
-            # - sleep 5            
-            # - quality_status='url -s -u  $Sonar_AccessToken: $Sonar_Host/api/qualitygates/project_status?projectKey=$Sonar_Project | jq '.projectStatus.status' | tr -d '"'`
-            # - echo $quality_status
-            # - if [ "$quality_status" = "OK" ] then
-            #     exit 0
-            #   elif [ "$quality_status" = "ERROR" ] then
-            #     exit 1
-            #   fi           
-
+            
+            - sleep 5 #let the sonar scan complete            
+            - curl -u $Sonar_AccessToken:'' $Sonar_Host/api/qualitygates/project_status?projectKey=$Sonar_Project > result.json
+            #- cat result.json
+            - quality_status = $(jq -r '.projectStatus.status' result.json)
+            - echo $quality_status
+            - |
+                if [ $quality_status = OK ] ; then     
+                    echo "in quality_status OK condition"  
+                elif [ $quality_status = "ERROR" ]; then
+                    echo "in quality_status ERROR or WARN condition"
+                    exit 1;                    
+                fi
             - dotnet publish --no-restore --output build_output
             # - dotnet publish -c release -o ./build_output ClassroomApp.csproj
             # - echo Building the Docker image...
@@ -58,15 +57,6 @@ phases:
     post_build:
         commands:
             - echo Build completed on `date`
-            #- quality_status=$(curl -u ${Sonar_AccessToken}: ${Sonar_Host}/api/qualitygates/project_status?projectKey=${Sonar_Project} | jq -r '.projectStatus.status')
-            - curl -u $Sonar_AccessToken:'' $Sonar_Host/api/qualitygates/project_status?projectKey=$Sonar_Project > result.json
-            - cat result.json
-            - echo $result.json
-            - quality_status=$(curl -u ${Sonar_AccessToken}:'' ${Sonar_Host}/api/qualitygates/project_status?projectKey=${Sonar_Project} | jq -r '.projectStatus.status')
-            - echo $quality_status
-            - cat quality_status
-            #- if [ $quality_status = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ; fi
-            
             # - echo Pushing the Docker image...
             # - docker push $REPOSITORY_URI:latest
             # - docker push $REPOSITORY_URI:$IMAGE_TAG
